INSERT INTO tweet(tweet, date, userId) VALUES
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),
("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", now(), 1 ),
("Nunc vel mauris volutpat, congue ligula eget", now(), 1 ),
("Vestibulum consequat congue tellus", now(), 1 ),
("Quisque aliquet nisi ut massa egestas", now(), 1 ),
(" Phasellus nec dui in elit volutpat volutpat et vitae mauris", now(), 1 ),
("Sed eu fringilla sapien, vel pellentesque nisi.", now(), 1 ),
("Duis egestas tortor sed erat consectetur", now(), 1 ),

("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),
("Quisque in accumsan felis, a venenatis turpis", now(), 2 ),
("Pellentesque tristique fermentum leo sed facilisis.", now(), 2 ),
("Nam vehicula hendrerit fringilla. Fusce neque sapien", now(), 2 ),
("Sed ac tristique diam.", now(), 2 ),
("Donec sagittis sapien non mauris egestas rhoncus.", now(), 2 ),

("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),
("Nulla facilisi. Integer in velit at quam viverra feugiat", now(), 3 ),
("Cum sociis natoque penatibus et magnis dis parturient", now(), 3 ),
("Sed ornare lacus odio, ac hendrerit nibh tempus ac", now(), 3 ),
("Donec augue turpis, fermentum id elementum sed, ", now(), 3 ),


("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 ),
("Curabitur sagittis ipsum nibh,", now(), 3 ),
("Proin vel purus erat. Etiam id ante eget dolor tempor", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Donec ultricies semper nibh, eget vulputate", now(), 4 ),
("Nam congue felis convallis magna interdum", now(), 4 )